### ISSUE TITLE
kf5-kmymoney build failure

### ISSUE THREAD

**Issue by myzinsky** [KDE-mac/homebrew-kde#61]
I tried to compile kmymoney:

```
Warning: Calling Formula.factory is deprecated!
Use Formulary.factory instead.
/usr/local/Library/Taps/haraldf/homebrew-kf5/kf5-kdoctools.rb:25:in `install'
Please report this to the haraldf/kf5 tap!

Warning: Calling Formula.factory is deprecated!
Use Formulary.factory instead.
/usr/local/Library/Taps/haraldf/homebrew-kf5/kf5-kdoctools.rb:26:in `install'
Please report this to the haraldf/kf5 tap!

==> cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/kf5-kdoctools/5.22.0 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VER
==> make install
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink share/man/de/man1/checkXML5.1
/usr/local/share/man/de/man1 is not writable.

You can try again using:
  brew link kf5-kdoctools
```

...

```
Error: An unexpected error occurred during the `brew link` step
The formula built, but is not symlinked into /usr/local
Permission denied - /usr/local/share/man/de/man8
Error: Permission denied - /usr/local/share/man/de/man8
```

do you have an idea?

**Comment by sl1pkn07** [comment]
time and versions is passed. @myzinsky can you try with newer versions?

**Comment by myzinsky** [comment]
yes, my last attempt some days ago was leading to this issue:

https://github.com/KDE-mac/homebrew-kde/issues/291#issuecomment-485238541

It seams to be fixed now, so I will try it again!

**Comment by myzinsky** [comment]
Now there is this issue:

```bash
==> Pouring libical-3.0.4_2.mojave.bottle.tar.gz
🍺  /usr/local/Cellar/libical/3.0.4_2: 170 files, 4.9MB
==> Installing kde-mac/kde/kmymoney
==> Downloading https://download.kde.org/stable/kmymoney/5.0.3/src/kmymoney-5.0.3.tar.xz
==> Downloading from http://ftp.gwdg.de/pub/linux/kde/stable/kmymoney/5.0.3/src/kmymoney-5.0.3.tar.xz
######################################################################## 100.0%
==> cmake -G Ninja .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/kmymoney/5.0
Last 15 lines from /Users/myzinsky/Library/Logs/Homebrew/kmymoney/01.cmake:
-- Could NOT find KF5IdentityManagement (missing: KF5IdentityManagement_DIR)
-- Could NOT find KF5IdentityManagement: found neither KF5IdentityManagementConfig.cmake nor kf5identitymanagement-config.cmake
-- Could NOT find KF5Activities (missing: KF5Activities_DIR)
-- Could NOT find KF5Activities: found neither KF5ActivitiesConfig.cmake nor kf5activities-config.cmake
CMake Error at /usr/local/Cellar/cmake/3.14.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find KF5 (missing: ItemModels) (found suitable version "5.57.0",
  minimum required is "5.2")
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.14.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/ECM/find-modules/FindKF5.cmake:110 (find_package_handle_standard_args)
  CMakeLists.txt:67 (find_package)


-- Configuring incomplete, errors occurred!
See also "/tmp/kmymoney-20190422-59715-1rwkssg/kmymoney-5.0.3/build/CMakeFiles/CMakeOutput.log".

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
  https://github.com/KDE-mac/homebrew-kde/issues

These open issues may also help:
kf5-kmymoney build failure https://github.com/KDE-mac/homebrew-kde/issues/61
kf5-kmymoney crashing https://github.com/KDE-mac/homebrew-kde/issues/58
kmymoney kf5.kio.core: couldn't create slave: "Unknown protocol 'file'." https://github.com/KDE-mac/homebrew-kde/issues/260
```

**Comment by myzinsky** [comment]
Here the full list from the log:

```bash
 34 -- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2")
 35 -- Could NOT find QGpgme (missing: QGpgme_DIR)
 36 -- Checking for module 'sqlcipher'
 37 --   No package 'sqlcipher' found
 38 -- Found KF5Archive: /usr/local/lib/cmake/KF5Archive/KF5ArchiveConfig.cmake (found version "5.57.0")
 39 -- Found KF5CoreAddons: /usr/local/lib/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake (found version "5.57.0")
 40 -- Found KF5Config: /usr/local/lib/cmake/KF5Config/KF5ConfigConfig.cmake (found version "5.57.0")
 41 -- Found KF5ConfigWidgets: /usr/local/lib/cmake/KF5ConfigWidgets/KF5ConfigWidgetsConfig.cmake (found version "5.57.0")
 42 -- Found Gettext: /usr/local/opt/gettext/bin/msgmerge (found version "0.19.8.1")
 43 -- Found KF5I18n: /usr/local/lib/cmake/KF5I18n/KF5I18nConfig.cmake (found version "5.57.0")
 44 -- Found KF5Completion: /usr/local/lib/cmake/KF5Completion/KF5CompletionConfig.cmake (found version "5.57.0")
 45 -- Found KF5KCMUtils: /usr/local/lib/cmake/KF5KCMUtils/KF5KCMUtilsConfig.cmake (found version "5.57.0")
 46 -- Could NOT find KF5ItemModels (missing: KF5ItemModels_DIR)
 47 -- Could NOT find KF5ItemModels: found neither KF5ItemModelsConfig.cmake nor kf5itemmodels-config.cmake
 48 -- Found KF5ItemViews: /usr/local/lib/cmake/KF5ItemViews/KF5ItemViewsConfig.cmake (found version "5.57.0")
 49 -- Found KF5Service: /usr/local/lib/cmake/KF5Service/KF5ServiceConfig.cmake (found version "5.57.0")
 50 -- Found KF5Wallet: /usr/local/lib/cmake/KF5Wallet/KF5WalletConfig.cmake (found version "5.57.0")
 51 -- Found KF5IconThemes: /usr/local/lib/cmake/KF5IconThemes/KF5IconThemesConfig.cmake (found version "5.57.0")
 52 -- Found KF5XmlGui: /usr/local/lib/cmake/KF5XmlGui/KF5XmlGuiConfig.cmake (found version "5.57.0")
 53 -- Found KF5TextWidgets: /usr/local/lib/cmake/KF5TextWidgets/KF5TextWidgetsConfig.cmake (found version "5.57.0")
 54 -- Found KF5Notifications: /usr/local/lib/cmake/KF5Notifications/KF5NotificationsConfig.cmake (found version "5.57.0")
 55 -- Found KF5KIO: /usr/local/lib/cmake/KF5KIO/KF5KIOConfig.cmake (found version "5.57.0")
 56 -- Found KF5DocTools: /usr/local/lib/cmake/KF5DocTools/KF5DocToolsConfig.cmake (found version "5.57.0")
 57 -- Could NOT find KF5Holidays (missing: KF5Holidays_DIR)
 58 -- Could NOT find KF5Holidays: found neither KF5HolidaysConfig.cmake nor kf5holidays-config.cmake
 59 -- Could NOT find KF5Contacts (missing: KF5Contacts_DIR)
 60 -- Could NOT find KF5Contacts: found neither KF5ContactsConfig.cmake nor kf5contacts-config.cmake
 61 -- Could NOT find KF5Akonadi (missing: KF5Akonadi_DIR)
 62 -- Could NOT find KF5Akonadi: found neither KF5AkonadiConfig.cmake nor kf5akonadi-config.cmake
 63 -- Could NOT find KF5IdentityManagement (missing: KF5IdentityManagement_DIR)
 64 -- Could NOT find KF5IdentityManagement: found neither KF5IdentityManagementConfig.cmake nor kf5identitymanagement-config.cmake
 65 -- Found KF5Activities: /usr/local/lib/cmake/KF5Activities/KF5ActivitiesConfig.cmake (found version "5.57.0")
 66 CMake Error at /usr/local/Cellar/cmake/3.14.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
 67   Could NOT find KF5 (missing: ItemModels) (found suitable version "5.57.0",
 68   minimum required is "5.2")
 69 Call Stack (most recent call first):
 70   /usr/local/Cellar/cmake/3.14.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
 71   /usr/local/share/ECM/find-modules/FindKF5.cmake:110 (find_package_handle_standard_args)
 72   CMakeLists.txt:67 (find_package)
```

**Comment by sl1pkn07** [comment]
try now. i add kitemmodels and sqlcipher to depends. 

The rest of them (kf5hollydays, kf5contacts kf5akonadi and kf5identitymanagement) is part of kdepim and unabliable in this moment in this brew

also gpgme seems need a little setup. i'm try it to solve

greetings

**Comment by myzinsky** [comment]
brew install ```kde-mac/kde/kf5-kitemmodels``` it compiles and starts. But it is so buggy ... even more buggy than the preview versions of the kmymoney website:

https://binary-factory.kde.org/view/MacOS/job/KMyMoney_Nightly_macos/

Best,
Matthias

**Comment by sl1pkn07** [comment]
https://github.com/Homebrew/homebrew-core/issues/39173
for the qgpgme bindings

**Comment by sl1pkn07** [comment]
the maim problem seems fixed (fail build)

close the thread

greetings
